### ISSUE TITLE
Wiki page link for migration guide 2->3 is broken

### ISSUE THREAD

**Issue by alaershov** [stephanenicolas/toothpick#358]
Hi! Awesome job on TP 3!

Would be great to fix wiki link for migration guide, it's currently:
`https://github.com/stephanenicolas/toothpick/wiki/TP-2---TP-3:-Migration-Guide`
but should be
`https://github.com/stephanenicolas/toothpick/wiki/TP-2----TP-3:-Migration-Guide`

**Comment by dlemures** [comment]
It should work now. Thx for reporting it!

**Comment by alexfu** [comment]
The link on the wiki is still broken btw...

![Kapture 2019-11-24 at 11 11 08](https://user-images.githubusercontent.com/987398/69497451-346d5b80-0eab-11ea-857a-937ea00039c5.gif)

I checked the link and it is still using: 
https://github.com/stephanenicolas/toothpick/wiki/TP-2---TP-3:-Migration-Guide

**Comment by stephanenicolas** [comment]
Thx Alex, Daniel had fix only one of the 2 occurrences. I just fixed the
other one, that you had just mentioned.
